image: node:18-alpine

pages:
  script:
    - npm install hexo-cli gulp-cli -g
    - test -e package.json && npm install
    - hexo generate
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
    key: project
  only:
    - master